export const locationData = {
  partner: {
    title: 'France',
    address: {
      organization: 'French Example Ltd.',
      givenName: 'Mr. Paris',
      familyName: 'Bagels',
      addressLine1: '1 East Road',
      addressLine2: 'General District',
      postalCode: '1001',
      locality: 'Paris',
      dependentLocality: null,
      administrativeArea: null,
      country: 'France',
    },
    phone: '+1 234 567 890',
    fax: '+1 234 567 890',
    email: 'contact@example.com',
    website: 'www.example.com',
  },
  regionalOffice: {
    title: 'Example Headquarters',
    address: {
      organization: 'Example AG',
      givenName: '',
      familyName: '',
      addressLine1: '123 Fake Street',
      addressLine2: '',
      postalCode: '8005',
      locality: 'Zurich',
      dependentLocality: null,
      administrativeArea: null,
      country: 'Switzerland',
    },
    phone: '+41 12 345 678',
    fax: '+41 12 345 678',
    website: 'https://www.example.com',
    email: 'info@example.com',
  },
};
